
services:
  db:
    image: mysql:9.3.0
    container_name: raffle-mysql
    restart: "no"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TIME_ZONE}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
